spring:
  application:
    name: eureka-client-demo

server:
  port: 9091

eureka:
  instance:
    appname: eureka-client
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka
