spring:
  application:
    name: open-feign-demo

server:
  port: 9092

eureka:
  instance:
    appname: open-feign-demo
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka
